"""PikPak-specific service layer — offline download via rclone backend addurl.

This module bridges the CloudDriveService interface with rclone's pikpak: backend.
"""

from __future__ import annotations

from src.core.logger import get_logger
from src.core.config import Config

logger = get_logger("pikpak_service")


def cloud_download_add(urls: list[str], folder: str = "/My Pack") -> str:
    """Create an offline download task on PikPak using rclone backend addurl.

    Creates a job record in the cloud download manager and executes rclone.

    Args:
        urls: List of HTTP/magnet URLs to download.
        folder: Destination folder on PikPak (e.g. /My Pack or /movies/2026).

    Returns:
        Task ID as string (UUID generated by the system).
    """
    from src.services.cloud_download_manager import get_cloud_download_manager

    # Create tracking job first
    mgr = get_cloud_download_manager()
    job = mgr.create_job(urls, folder)

    try:
        cfg = Config.get()
        adapter = __import__("src.adapters.rclone_adapter", fromlist=["RcloneAdapter"]).RcloneAdapter(
            rclone_path=cfg.rclone_path,
            remote_name="pikpak:",
        )
        result = adapter.backend_addurl(folder, urls[0])
        mgr.update_status(job.task_id, "running")
        logger.info(f"Cloud download task started: {job.task_id}, rclone result: {result}")
        return job.task_id
    except Exception as e:
        logger.error(f"Cloud download failed: {job.task_id}, error: {e}")
        mgr.update_status(job.task_id, "failed", str(e))
        raise
