"""Fernet encryption utilities.

Implements SC-001: AES-128-CBC + HMAC-SHA256 via cryptography.Fernet.
- encrypt(plaintext: str) -> str   — returns base64 ciphertext
- decrypt(ciphertext: str) -> str  — returns original plaintext
- must_call_configure(key: str) before use
"""

from cryptography.fernet import Fernet, InvalidToken
from typing import Optional

from .exceptions import (
    EncryptionKeyNotSetError,
    EncryptionDecryptError,
    EncryptionEncryptError,
)

_fernet: Optional[Fernet] = None


def configure(key: str) -> None:
    """Initialize Fernet with the provided base64-encoded key.

    Args:
        key: A Fernet-compatible base64 key (44 chars, e.g. generated by Fernet.generate_key()).

    Raises:
        EncryptionKeyNotSetError: If key is empty or whitespace-only.
    """
    if not key or not key.strip():
        raise EncryptionKeyNotSetError(
            message="Fernet encryption key is not configured.",
            detail="Set 'encryption.salt' in your config file.",
        )
    global _fernet
    _fernet = Fernet(key.encode())


def encrypt(plaintext: str) -> str:
    """Encrypt a string and return a base64-encoded ciphertext.

    Args:
        plaintext: The string to encrypt.

    Returns:
        Base64-encoded ciphertext.

    Raises:
        EncryptionKeyNotSetError: If configure() has not been called.
        EncryptionEncryptError: If encryption fails.
    """
    if _fernet is None:
        raise EncryptionKeyNotSetError()
    try:
        return _fernet.encrypt(plaintext.encode()).decode()
    except Exception as e:
        raise EncryptionEncryptError(
            message="Failed to encrypt data.",
            detail=str(e),
        )


def decrypt(ciphertext: str) -> str:
    """Decrypt a base64-encoded ciphertext and return the plaintext string.

    Args:
        ciphertext: Base64-encoded ciphertext from encrypt().

    Returns:
        Decrypted plaintext string.

    Raises:
        EncryptionKeyNotSetError: If configure() has not been called.
        EncryptionDecryptError: If decryption fails (invalid token or corrupted data).
    """
    if _fernet is None:
        raise EncryptionKeyNotSetError()
    try:
        return _fernet.decrypt(ciphertext.encode()).decode()
    except InvalidToken as e:
        raise EncryptionDecryptError(
            message="Failed to decrypt data.",
            detail="Invalid or expired token.",
        )
    except Exception as e:
        raise EncryptionDecryptError(
            message="Failed to decrypt data.",
            detail=str(e),
        )
